ibaseURL: "https://federicopilla.github.io/website/"
title: "Federico Pilla"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 


params:
    description: "This website hosts Federico Pilla's research, CV, and contact information."
    author: Federico Pilla
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Federico Pilla
          subtitle: ">
              Ph.D. Candidate, University of Surrey<br>
              Macro-Labor Economics, Family Economics, Time Series Analysis<br><br>
              Welcome! Iâ€™m Federico Pilla, a 4th-year PhD student in Economics at the University of Surrey, supervised by Rigas Oikonomou and Harris Dellas.<br>
              My research interests are in **labor economics**. I study how technological, demographic, and social changes shape households' labour supply decisions.<br>
              Previously, I worked as a PhD Intern at the Bank of England (Structural Economic Analysis Division).
             "
          imageUrl: "Federico_Pilla_photo.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Curriculum vitae
              url: fp_cv.pdf 
            - name: Location
              url: location/
            - name: Papers
              url: papers/
    
              
    socialIcons:
        - name: CV
          url:  "fp_cv.pdf"
        - name: Email
          url: mailto:f.pilla@surrey.ac.uk
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/federicopilla
        - name: Twitter
          url: https://x.com/federico_pilla
        - name: Linkedin
          url: https://www.linkedin.com/in/federico-pilla-88374b108/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Federico Pilla"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
